CREATE TABLE IF NOT EXISTS accounts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    -- The account number is generated by concatenating '01' with the zero-padded ID of the account.
	account_number TEXT GENERATED ALWAYS AS ('01' || printf('%06d', id)) STORED,
	sort_code VARCHAR(8) NOT NULL,
    user_id TEXT NOT NULL,
	name VARCHAR(255) NOT NULL,
	account_type VARCHAR(255) NOT NULL,
	balance INTEGER DEFAULT 0 CHECK(balance >= 0 AND balance <= 1000000),
	currency VARCHAR(3) NOT NULL,
    minor_unit INTEGER NOT NULL DEFAULT 100, -- Default to 100 for currencies like USD, GBP, EUR
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE RESTRICT
);